### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by 0Collin** [0Collin/apcsa-final-db#1]
- [ ] Install Gradle within Repl.it
 - [ ] Use the google sheets API https://developers.google.com/sheets/api/quickstart/java 
 - [ ] Create credentials for the sheet https://developers.google.com/workspace/guides/create-credentials 
 - [ ] Grab prep and sample from the sheets documentation
 - [ ] Test to make sure it works, then modify it to fit what we need to do.

**Comment by 0Collin** [comment]
Gradle doesn't work within Repl.it so we might have to edit code offline and then push our changes onto the github when we're done. I'll ask Trahan to see if there's anything we can do about it but when I looked around on forums it seems that the general consensus is you can't install gradle on Repl.it.
